//  THIS CODE WAS GENERATED BY AI
"use client"
import Link from 'next/link';
import React from 'react';
import { Button, buttonVariants } from '@/components/ui/button';
import { IconSeparator } from '@/components/ui/icons';
import { createClientComponentClient } from '@supabase/auth-helpers-nextjs';
import Avatar from '@mui/material/Avatar';
import { Database } from '@/lib/database.types';
import GitHubIcon from '@mui/icons-material/GitHub'; // Import the GitHub icon from MUI
import { useRouter } from 'next/navigation';

export function Header(cookies: any) {
  const supabase = createClientComponentClient<Database>();
  const [session, setSession] = React.useState<any>(undefined);
  const router = useRouter()
  React.useEffect(() => {
    supabase.auth.onAuthStateChange((event, session) => {
      setSession(session);
    });
  }, [session]);

  // Handler for the "Log Out" button
  const handleLogOut = async () => {
    await supabase.auth.signOut();
    router.push('/sign-in')
  };

  return (
    <header
      style={{
        backgroundImage: 'linear-gradient(to right, #f5f7fa, #c3cfe2)',
      }}
      className="sticky top-0 z-50 flex items-center justify-between w-full h-16 px-4 border-b shrink-0 bg-gradient-to-b from-background/10 via-background/50 to-background/80 backdrop-blur-xl"
    >
      <div className="flex items-center">
        <div className="flex items-center">
          {session?.user ? (
            <>
              <Avatar
                alt={session.user.user_metadata.name}
                src={session.user.user_metadata.avatar_url}
              />
              <IconSeparator className="w-6 h-6 text-muted-foreground/50" />
              <Link href="/">Home</Link>
            </>
          ) : (
            <></>
          )}
        </div>
      </div>
      <div className="flex items-center justify-end space-x-3">
        <a
          href="https://github.com/taimoor0217/co-poet" // Replace with your GitHub repository URL
          target="_blank"
          rel="noopener noreferrer"
          className="flex items-center" // Add this class to center the text and icon
        >
          <GitHubIcon />
        </a>
        <IconSeparator className="w-6 h-6 text-muted-foreground/50" />
        {session?.user ? (
          <div  onClick={handleLogOut}>
            Sign Out
          </div>

        ) : (<></>)}
      </div>
    </header>
  );
}
